# Generated by Django 5.2.5 on 2025-11-03 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourservice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About_d',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('About_d_title', models.CharField(max_length=200)),
                ('About_d_description', models.TextField()),
                ('About_d_img1', models.FileField(default=None, max_length=250, null=True, upload_to='About')),
                ('About_d_img2', models.FileField(default=None, max_length=250, null=True, upload_to='About')),
            ],
        ),
        migrations.CreateModel(
            name='Product_d',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_d_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Product_d_name', models.CharField(max_length=200)),
                ('Product_d_img', models.FileField(default=None, max_length=250, null=True, upload_to='Product')),
                ('Product_d_description', models.TextField()),
            ],
        ),
    ]
