# Generated by Django 5.2.5 on 2025-11-03 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourservice', '0002_about_d_product_d'),
    ]

    operations = [
        migrations.AddField(
            model_name='about_d',
            name='feature_1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='about_d',
            name='feature_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='about_d',
            name='feature_3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='about_d',
            name='feature_4',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
