# Generated by Django 5.2.5 on 2025-11-10 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourservice', '0004_blog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.AlterField(
            model_name='product_d',
            name='Product_d_price',
            field=models.CharField(max_length=200),
        ),
    ]
