# Generated by Django 5.2.5 on 2025-12-01 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourservice', '0007_review_d'),
    ]

    operations = [
        migrations.CreateModel(
            name='blog_d',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_d_img', models.FileField(default=None, max_length=250, null=True, upload_to='blog')),
                ('blog_d_title', models.CharField(max_length=300)),
                ('blog_d_description', models.TextField()),
            ],
        ),
    ]
