# Generated by Django 5.2.5 on 2025-12-04 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourservice', '0008_blog_d'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_title', models.CharField(max_length=150)),
                ('service_desc', models.TextField()),
                ('service_read_link', models.CharField(max_length=150)),
            ],
        ),
        migrations.DeleteModel(
            name='About_d',
        ),
        migrations.DeleteModel(
            name='blog_d',
        ),
        migrations.DeleteModel(
            name='Contactform',
        ),
        migrations.DeleteModel(
            name='Product_d',
        ),
        migrations.DeleteModel(
            name='Review_d',
        ),
        migrations.DeleteModel(
            name='Team_d',
        ),
    ]
