# Generated by Django 5.2.5 on 2025-12-04 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourservice', '0009_service_delete_about_d_delete_blog_d_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='About_d',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('About_d_title', models.CharField(max_length=200)),
                ('About_d_description', models.TextField()),
                ('feature_1', models.CharField(blank=True, max_length=100, null=True)),
                ('feature_2', models.CharField(blank=True, max_length=100, null=True)),
                ('feature_3', models.CharField(blank=True, max_length=100, null=True)),
                ('feature_4', models.CharField(blank=True, max_length=100, null=True)),
                ('About_d_img1', models.FileField(default=None, max_length=250, null=True, upload_to='About')),
                ('About_d_img2', models.FileField(default=None, max_length=250, null=True, upload_to='About')),
            ],
        ),
    ]
