# Generated by Django 5.2.5 on 2025-12-04 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ourservice', '0010_about_d'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about_d',
            name='About_d_img2',
        ),
        migrations.RemoveField(
            model_name='about_d',
            name='feature_1',
        ),
        migrations.RemoveField(
            model_name='about_d',
            name='feature_2',
        ),
        migrations.RemoveField(
            model_name='about_d',
            name='feature_3',
        ),
        migrations.RemoveField(
            model_name='about_d',
            name='feature_4',
        ),
    ]
