# Generated by Django 5.2.5 on 2025-12-04 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourservice', '0011_remove_about_d_about_d_img2_remove_about_d_feature_1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='blog_d',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_d_img', models.FileField(default=None, max_length=250, null=True, upload_to='blog')),
                ('blog_d_title', models.CharField(max_length=300)),
                ('blog_d_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Contactform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Product_d',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_d_price', models.CharField(max_length=200)),
                ('Product_d_name', models.CharField(max_length=200)),
                ('Product_d_img', models.FileField(default=None, max_length=250, null=True, upload_to='Product')),
                ('Product_d_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Review_d',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Review_d_img', models.FileField(default=None, max_length=250, null=True, upload_to='Review')),
                ('Review_d_name', models.CharField(max_length=200)),
                ('Review_d_position', models.CharField(max_length=200)),
                ('Review_d_message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Team_d',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Team_d_img', models.FileField(default=None, max_length=250, null=True, upload_to='Team')),
                ('Team_d_name', models.CharField(max_length=200)),
                ('Team_d_position', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.AddField(
            model_name='about_d',
            name='About_d_img2',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='About'),
        ),
        migrations.AddField(
            model_name='about_d',
            name='feature_1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='about_d',
            name='feature_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='about_d',
            name='feature_3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='about_d',
            name='feature_4',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
