# Generated by Django 5.2.5 on 2025-11-10 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourservice', '0005_delete_blog_alter_product_d_product_d_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team_d',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Team_d_img', models.FileField(default=None, max_length=250, null=True, upload_to='Team')),
                ('Team_d_name', models.CharField(max_length=200)),
                ('Team_d_position', models.CharField(max_length=200)),
            ],
        ),
    ]
