# Generated by Django 5.2.5 on 2025-11-10 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourservice', '0006_team_d'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review_d',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Review_d_img', models.FileField(default=None, max_length=250, null=True, upload_to='Review')),
                ('Review_d_name', models.CharField(max_length=200)),
                ('Review_d_position', models.CharField(max_length=200)),
                ('Review_d_message', models.TextField()),
            ],
        ),
    ]
